version: '3.9'
services:
  mysql:
    image: mariadb
    container_name: mysql
    environment:
      - MARIADB_ROOT_PASSWORD=orico
      - MARIADB_DATABASE=orico
      - MARIADB_USER=orico
      - MARIADB_PASSWORD=orico
    ports:
      - 33060:3306
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
