version: '3.9'
services:

  zookeeper:
    image: zookeeper
    container_name: zookeeper
    ports:
      - 2181:2181
    volumes:
      - zookeeper:/data

  kafka1:
    image: bitnami/kafka
    container_name: kafka1
    ports:
      - 9092:9092
    volumes:
      - kafka1:/bitnami/kafka/data
      - kafka-logs1:/tmp/kafka-logs
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
      - zookeeper

  kafka2:
    image: bitnami/kafka
    container_name: kafka2
    ports:
      - 9093:9093
    volumes:
      - kafka2:/bitnami/kafka/data
      - kafka-logs2:/tmp/kafka-logs
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9093
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
      - zookeeper

volumes:
  zookeeper:
  kafka1:
  kafka-logs1:
  kafka2:
  kafka-logs2:
